### ISSUE TITLE
Experiments work on machine with older env, but not another with newer env

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#254]
I have some EMA+pynetlogo code that runs on my desktop in a somewhat older environment, but not on my laptop in a newer environment. Testing various example models, the pynetlogo SALib demo (https://github.com/quaquel/pyNetLogo/blob/master/examples/predprey_salib_multiprocessing.py) works only on the desktop, but https://github.com/quaquel/EMAworkbench/blob/master/ema_workbench/examples/example_netlogo.py works on both.

Exemplary traceback from the laptop for the pynetlogo SALib demo:

```
(robustresilience39) C:\Local\Testing>python predprey_salib_multiprocessing.py
C:\Local\Testing\predprey_salib_multiprocessing.py:81: DeprecationWarning: `salib.sample.saltelli` will be removed in SALib 1.5. Please use `salib.sample.sobol`
  param_values = saltelli.sample(problem, n, calc_second_order=True)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Local\Testing\predprey_salib_multiprocessing.py", line 48, in run_simulation
    counts = netlogo.repeat_report(["count sheep", "count wolves"], 100)
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\site-packages\pynetlogo\core.py", line 557, in repeat_report
    os.remove(value)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Local\\Testing\\is21qc9b\\tmp273ew_1s.txt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Local\Testing\predprey_salib_multiprocessing.py", line 89, in <module>
    for entry in executor.map(run_simulation, experiments.to_dict("records")):
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
PermissionError: [Errno 13] The process cannot access the file because it is being used by another process: 'C:\\Local\\Testing\\is21qc9b\\tmp273ew_1s.txt'
```

My suspicion is that something related to working directories has changed between package versions, but I might be completely off. I looked at the changelogs for pynetlogo and EMA but didn't spot anything that seemed relevant. Does this problem ring a bell?

Desktop, Win10 Enterprise
ema-workbench             2.2.0                    pypi_0    pypi
multiprocess              0.70.13                  pypi_0    pypi
pynetlogo                 0.4.2                    pypi_0    pypi
python                    3.10.6          h9a09f29_0_cpython    conda-forge

Laptop, Win10 Enterprise
ema-workbench             2.3.0                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
pynetlogo                 0.5.1                    pypi_0    pypi
python                    3.9.16               h6244533_2

**Comment by quaquel** [comment]
Something did change in `repeat_report`. I moved to using tempfiles from files whose filename was based on the name of the outcome of interest. What I find strange is that different, separately spawned processes end up using the exact same tempdir and tempfile.

**Comment by steipatr** [comment]
First of all, I appreciate your support on all things EMA and pynetlogo. Thank you for your quick replies and insightful suggestions.

I tried adding the process ID (with `os.getpid()`) as a suffix to both `mkdtemp` and `mkstemp` in `repeat_report` to no avail:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Local\Testing\predprey_salib_multiprocessing.py", line 47, in run_simulation
    counts = netlogo.repeat_report(["count sheep", "count wolves"], 100)
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\site-packages\pynetlogo\core.py", line 553, in repeat_report
    os.remove(value)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Local\\Testing\\i8f_xyod-10180\\tmpme8gp6ok-10180.txt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Local\Testing\predprey_salib_multiprocessing.py", line 94, in <module>
    for entry in executor.map(run_simulation, experiments.to_dict("records")):
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\stein042\.conda\envs\robustresilience39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
PermissionError: [Errno 13] The process cannot access the file because it is being used by another process: 'C:\\Local\\Testing\\i8f_xyod-10180\\tmpme8gp6ok-10180.txt'
```

I also tried commenting out the temporary folder and file cleanup stuff in `repeat_report`. After which the code ran fine, although I also had to change around some output processing in https://github.com/quaquel/pyNetLogo/blob/master/examples/predprey_salib_multiprocessing.py#L50, from:

```
    results = pd.Series(
        [counts["count sheep"].values.mean(), counts["count wolves"].values.mean()],
        index=["Avg. sheep", "Avg. wolves"],
    )
    return results

```
to:
```
    results = pd.Series(
        [counts["count sheep"].mean(), counts["count wolves"].mean()],
        index=["Avg. sheep", "Avg. wolves"],
    )
```
due to error "numpy.ndarray object has no attribute values".

So perhaps the issue is somewhere in the temporary folder/file cleanup? Might be as simple as an identation error. Will dig around some more.

**Comment by quaquel** [comment]
ok, so this is clearly a pynetlogo rather than an EMA bug, and from the looks of it Windows specific.

**Comment by steipatr** [comment]
Yes I agree. I think that at owner level, it's possible to move issues between repos, perhaps this should be continued in the pynetlogo repo.
